apiVersion: apps/v1
kind: Deployment

metadata:
  name: trend-deployment
  namespace: trend
  labels:
    app: trend-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: trend-app

  template:
    metadata:
      labels:
        app: trend-app

    spec:
      containers:
        - name: trend-app
          image: naliniselv/trend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"

            limits:
              memory: "128Mi"
              cpu: "500m"